#!/usr/bin/env python3
# =============================================================================
# gh_project_render.py
# =============================================================================
#
# Pull live GitHub issue state for every issue referenced in the catalog
# (build-tools/properties.yaml) and render a coordination view
# (build-tools/static/mkdocs/docs/ledger-properties-issues.md):
# open/closed, assignees, links.
#
# This is the GitHub -> repo direction. Formal status (proved/stated) is owned by
# scan_properties.py and lives in ledger-properties-dashboard.md; this file is the
# *coordination* companion (who/where/open-closed), kept separate so the two
# generators never fight over one file.
#
# Auth/runtime: requires `gh` authenticated with read access to the repo. Run
# locally. (`--check` is for local verification; it needs network, so it is not
# wired into CI — the no-network CI gate is scan_properties.py --check.)
#
#   python3 build-tools/scripts/property-tracking/gh_project_render.py            # write issues view
#   python3 build-tools/scripts/property-tracking/gh_project_render.py --check    # verify up-to-date
#
# Dependencies: Python 3.8+, PyYAML, gh.
# -----------------------------------------------------------------------------

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("error: PyYAML is required (pip install pyyaml)")

# Reuse the single source of truth for status derivation (same directory).
sys.path.insert(0, str(Path(__file__).resolve().parent))
from scan_properties import derive_status, display_path  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CATALOG = REPO_ROOT / "build-tools" / "properties.yaml"
DEFAULT_OUT = (REPO_ROOT / "build-tools" / "static" / "mkdocs" / "docs"
               / "ledger-properties-issues.md")

BEGIN = "<!-- BEGIN GENERATED: issues (gh_project_render.py) -->"
END = "<!-- END GENERATED: issues (gh_project_render.py) -->"

PREAMBLE = """\
# Ledger properties — issue tracker view

Live GitHub state for every issue referenced by the property catalog
(`build-tools/properties.yaml`), generated by
`build-tools/scripts/property-tracking/gh_project_render.py`. The *formal* status (proved/stated)
lives in `ledger-properties-dashboard.md`; this file is the coordination companion.

"""


def gh_issue(repo: str, number: int) -> dict:
    proc = subprocess.run(
        ["gh", "api", f"repos/{repo}/issues/{number}"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        reason = next((ln.strip() for ln in (proc.stderr or "").splitlines() if ln.strip()),
                      f"gh exited {proc.returncode}")
        return {"ok": False, "error": reason,
                "number": number, "title": "(could not fetch)", "state": "unknown",
                "assignees": [], "html_url": ""}
    d = json.loads(proc.stdout)
    return {
        "ok": True,
        "number": number,
        "title": d.get("title", ""),
        "state": d.get("state", "unknown"),
        "assignees": [a["login"] for a in d.get("assignees", [])],
        "html_url": d.get("html_url", ""),
    }


def render_region(cat: dict, repo: str):
    """Render the generated region; returns (text, fetched_ok, fetch_failed).

    Logs one ✅/❌ line per issue to stderr as it fetches, so a run shows
    progress instead of silence."""
    n_ok = n_fail = 0
    lines = [BEGIN, "",
             "_Generated by `build-tools/scripts/property-tracking/gh_project_render.py` — do not edit by hand._", ""]
    by_era = {era: [] for era in cat["meta"]["eras"]}
    for p in cat["properties"]:
        status = derive_status(p.get("module") or "")[0]
        for num in (p.get("issues") or []):
            by_era.setdefault(p["era"], []).append((num, p["id"], status))

    for era, rows in by_era.items():
        if not rows:
            continue
        umb = (cat["meta"].get("umbrella_issues") or {}).get(era)
        header = f"### {era.capitalize()}"
        if umb:
            header += f" (umbrella #{umb})"
        lines += [header, "",
                  "| Issue | State | Catalog id | Status | Assignee | Title |",
                  "| --- | --- | --- | --- | --- | --- |"]
        for num, pid, status in sorted(set(rows)):
            info = gh_issue(repo, num)
            if info["ok"]:
                n_ok += 1
                print(f"✅ #{num} ({info['state']}) {pid}", file=sys.stderr)
            else:
                n_fail += 1
                print(f"❌ #{num} {pid} — {info['error']}", file=sys.stderr)
            state = "🟢 open" if info["state"] == "open" else (
                "🟣 closed" if info["state"] == "closed" else info["state"])
            who = ", ".join(info["assignees"]) or "—"
            link = f"[#{num}]({info['html_url']})" if info["html_url"] else f"#{num}"
            title = (info["title"] or "").replace("|", "\\|")
            lines.append(f"| {link} | {state} | `{pid}` | {status} | {who} | {title} |")
        lines.append("")
    lines.append(END)
    return "\n".join(lines), n_ok, n_fail


def build(existing: str | None, region: str) -> str:
    if existing and BEGIN in existing and END in existing:
        return existing.split(BEGIN)[0] + region + existing.split(END, 1)[1]
    return PREAMBLE + region + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Render live GitHub issue state for catalog properties.")
    ap.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--repo", default=None, help="OWNER/NAME (default: catalog meta.repo)")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    cat = yaml.safe_load(args.catalog.read_text(encoding="utf-8"))
    repo = args.repo or cat["meta"]["repo"]
    region, n_ok, n_fail = render_region(cat, repo)
    rendered = build(args.out.read_text(encoding="utf-8") if args.out.exists() else None, region)

    if args.check:
        stale = (not args.out.exists()) or (args.out.read_text(encoding="utf-8") != rendered)
        print("stale" if stale else "up-to-date", file=sys.stderr)
        return 1 if stale else 0

    args.out.write_text(rendered, encoding="utf-8")
    tally = f"{n_ok} ✅" + (f", {n_fail} ❌" if n_fail else "")
    print(f"wrote {display_path(args.out)} ({n_ok + n_fail} issue(s): {tally})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
