# mkdocs.yml

# Project information
site_name: Formal Ledger Specification
site_url: https://intersectmbo.github.io/formal-ledger-specifications/
site_description: Formal ledger specification and documentation.
site_author: Formal Methods Ledger Team
repo_url: https://github.com/IntersectMBO/formal-ledger-specifications

# Theme configuration (using mkdocs-material)
theme:
  name: material
  favicon: img/Cardano-RGB_Logo-Icon-White.svg
    # Optional features - see mkdocs-material docs for many more
  features:
    # - navigation.tabs
    - navigation.sections
    - toc.integrate # Integrate table of contents into left sidebar
    - content.tooltips
    - navigation.footer
    - navigation.tabs
    - content.code.copy # Adds copy buttons to code blocks

  # palette: # Optional: color scheme
  #   primary: indigo
  #   accent: indigo
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode

  # Font configuration (optional)
  font:
    text: Open Sans        # Other options: Cambria, Lato, Roboto
    code: Source Code Pro  # Other options: Roboto Mono, StrippedJuliaMono (if available via CSS)d?

  logo: img/Cardano-RGB_Logo-Icon-Blue.svg

# Navigation structure
nav:
  - Home: index.md

extra_css:
  # KaTeX CSS for math rendering
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
  # auto-generated by Agda fls backend (load after katex.css)
  # - css/Agda.css
  - css/custom.css

extra_javascript:
  # KaTeX JavaScript
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  # KaTeX configuration script (load after KaTeX)
  - js/katex-config.js
  # auto-generated by Agda fls backend (load after auto-render.js)
  - AgdaKaTeX.js
  - https://cdn.jsdelivr.net/npm/chart.js
  - js/custom.js

markdown_extensions:
  - admonition                # call-out boxes like !!! note
  - pymdownx.details
  - toc:                      # table of contents generation
      permalink: true         # anchor links to headers
  - pymdownx.superfences:     # syntax highlighting in code blocks
      custom_fences:
        - name: mermaid       # mermaid diagrams
          class: mermaid
  - attr_list                 # inline attributes like `code`{.class}
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.snippets:
      check_paths: true  # for debugging
      auto_append:
        - includes/links.md
  # Important: Use pymdownx.arithmatex with KaTeX
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - md_in_html
hooks:
  - hooks/agda_hidden_code.py
