# mkdocs.yml

# Project information
site_name: Formal Ledger Specification
site_url: https://intersectmbo.github.io/formal-ledger-specifications/
site_description: Formal ledger specification and documentation.
site_author: Formal Methods Ledger Team
repo_url: https://github.com/IntersectMBO/formal-ledger-specifications

# Use edit_uri_template to build file URLs (GitHub "blob" view)
edit_uri_template: 'blob/main/docs/{path}?plain=1'

# Theme configuration (using mkdocs-material)
theme:
  name: material
  custom_dir: overrides
  favicon: img/Cardano-RGB_Logo-Icon-White.svg
    # Optional features - see mkdocs-material docs for many more
  features:
    - toc.follow      # <-- keeps the right toc aligned with your position
    - content.tooltips
    - content.code.copy      # Adds copy buttons to code blocks
    # - content.action.edit    # Adds "Edit source" button (links to blobs)
    - content.action.view  # Adds "View source" button (links to raw files)
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs
    # - toc.integrate # <-- integrates toc into left sidebar
    # - navigation.expand # <-- all sections in the left-hand navigation are
    #                     #     expanded by default (their children are visible),
    #                     #     instead of collapsing siblings as you drill down.

  # palette: # Optional: color scheme
  #   primary: indigo
  #   accent: indigo
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode

  icon:
    edit: fontawesome/brands/github    # <- octocat icon (link to file)
    view: fontawesome/brands/github    #
    repo: fontawesome/brands/git-alt   # <- git icon (link to repo)


  # Font configuration (optional)
  font:
    text: Open Sans        # Other options: Cambria, Lato, Roboto
    code: Source Code Pro  # Other options: Roboto Mono, StrippedJuliaMono (if available via CSS)d?

  logo: img/Cardano-RGB_Logo-Icon-Blue.svg

# Navigation structure
nav:
  - Home: index.md

extra_css:
  # KaTeX CSS for math rendering
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
  # auto-generated by Agda fls backend (load after katex.css)
  # - css/Agda.css
  - css/custom.css

extra_javascript:
  # KaTeX JavaScript
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  # KaTeX configuration script (load after KaTeX)
  - js/katex-config.js
  # auto-generated by Agda fls backend (load after auto-render.js)
  - AgdaKaTeX.js
  - https://cdn.jsdelivr.net/npm/chart.js
  - js/custom.js

markdown_extensions:
  - admonition                # call-out boxes like !!! note
  - pymdownx.details
  - pymdownx.smartsymbols
  - toc:                      # table of contents generation
      permalink: true         # anchor links to headers
  - pymdownx.superfences:     # syntax highlighting in code blocks
      custom_fences:
        - name: mermaid       # mermaid diagrams
          class: mermaid
  - attr_list                 # inline attributes like `code`{.class}
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.snippets:
      check_paths: true  # for debugging
      auto_append:
        - includes/links.md
  # Important: Use pymdownx.arithmatex with KaTeX
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - md_in_html
hooks:
  - hooks/agda_hidden_code.py
  - hooks/agda_source_link.py
extra:
  source_branch: master
  source_overrides:
    # Special cases in which source file name is hard to infer from doc file name.
    # Syntax/Usage:
    #   doc file name: source file name
    index.md: README.md
    guide.md: CONTRIBUTING.md
    Definitions.md: build-tools/static/md/common/src/Definitions.md
    Notation.md: build-tools/static/md/common/src/Notation.md
    Properties.md: build-tools/static/md/common/src/Properties.md
