spec-version: 0.36.0
name: cardano-ledger-executable-spec
version: 0.1.0.0
license: NONE
language: Haskell2010
default-extensions:
  - DeriveGeneric
dependencies:
  - base
  - text
  - ieee
source-dirs:
  - src
library:
  exposed-modules:
    - MAlonzo.Code.Ledger.Foreign.API
