[book]
title = "Formal Ledger Specification"
authors = ["IOHK, Formal Methods Team"]
description = "The formal specification of the Cardano Ledger."
language = "en"
multilingual = false
src = "src" # default source directory

[output.html]
# HTML specific options (can be left default for now)
# e.g., theme = "my-theme-dir" if you add custom themes
# Add custom CSS and JS files here
# Paths are relative to the book's src directory (i.e., _build/mdbook/)
additional-css = ["src/css/custom.css", "src/css/mdbook-admonish.css", "src/css/Agda.css"]
# (order might matter if custom.css overrides Agda.css)
additional-js = ["src/js/custom.js"]
# We can add more files to these arrays if needed.

[output.pdf]
# This section enables PDF output via the mdbook-pdf backend.
# If we end up using a custom script (like our mdbook-to-pdf.sh), this is where
# the 'command' key would go.
output-file = "cardano-ledger-mdbook.pdf"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.3" # do not edit: managed by `mdbook-admonish install`
