# mkdocs.yml

# Project information
site_name: Formal Ledger Specification
site_url: https://intersectmbo.github.io/formal-ledger-specifications/
site_description: Formal ledger specification and documentation.
site_author: Formal Methods Ledger Team
repo_url: https://github.com/IntersectMBO/formal-ledger-specifications

# Theme configuration (using mkdocs-material)
theme:
  name: material
  # Optional features - see mkdocs-material docs for many more
  features:
    # - navigation.tabs
    - navigation.sections
    - toc.integrate # Integrate table of contents into left sidebar
    - content.tooltips
    - navigation.footer
  # palette: # Optional: color scheme
  #   primary: indigo
  #   accent: indigo

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: red

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  # Font configuration (optional)
  font:
    text: Cambria
    code: Source Code Pro
  #   text: Roboto
  #   code: Roboto Mono # Or perhaps StrippedJuliaMono if available via CSS?
extra:
  math:
    enable: true # This tells the Material theme to load KaTeX


# Navigation structure
nav:
  - Home: index.md

extra_css:
  # - https://unpkg.com/katex@0.16.10/dist/katex.min.css
  - css/custom.css
  - css/Agda.css

extra_javascript:
  # - https://unpkg.com/katex@0.16.10/dist/katex.min.js         # Core KaTeX library
  # - https://unpkg.com/katex@0.16.10/dist/contrib/auto-render.min.js # Auto-rendering script
  - js/custom.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true       # This is important for KaTeX with auto-render
  - admonition
  - pymdownx.details
  - toc:
      permalink: "#"
  # - toc:
  #     permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - attr_list
  - pymdownx.emoji
  - pymdownx.snippets:
      check_paths: true  # <-- Add this for debugging
      auto_append:
        - includes/links.md

watch:
  - includes

use_directory_urls: false
