name: Legacy LaTeX CI
on:
  push:
    branches:
    - legacy-latex
  # Allow manual triggering for testing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  formal-ledger-agda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/6c5963357f3c1c840201eda129a99d455074db04.tar.gz
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org/
      - name: Build formalLedger
        id: formalLedger
        run: |
          nix-build -A formalLedger -o outputs
      - name: Upload agda _build artifact
        uses: actions/upload-artifact@v4
        with:
          name: _build
          path: outputs/_build
      - name: Upload agda typechecking time artifact
        uses: actions/upload-artifact@v4
        with:
          name: typecheck.time
          path: outputs/typecheck.time

  # Build PDFs using legacy LaTeX source files
  cardano-ledger-pdf:
    needs: [formal-ledger-agda]
    uses: ./.github/workflows/build_artifact.yml
    with:
      target: cardano-ledger.pdf

  conway-ledger-pdf:
    needs: [formal-ledger-agda]
    uses: ./.github/workflows/build_artifact.yml
    with:
      target: conway-ledger.pdf

  # Optional: Keep HTML generation for completeness
  html:
    needs: [formal-ledger-agda]
    uses: ./.github/workflows/build_artifact.yml
    with:
      target: html

  upload-artifacts:
    # Always run to create the legacy-latex-artifacts branch
    needs: [formal-ledger-agda, cardano-ledger-pdf, conway-ledger-pdf, html]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set artifacts_branch variable
        id: set-artifacts-branch
        run: |
          printf "Creating legacy-latex-artifacts branch for PDF storage\n"
          echo "artifacts_branch=legacy-latex-artifacts" >> $GITHUB_OUTPUT
          printf "artifacts_branch: legacy-latex-artifacts\n"

      # Checkout legacy-latex-artifacts branch if it exists, otherwise create it
      - name: Checkout artifacts branch
        run: |
          if [[ -n "$(git ls-remote --heads origin "${ARTIFACTS_BRANCH}")" ]]; then
            echo "Checking out existing legacy-latex-artifacts branch"
            git checkout "${ARTIFACTS_BRANCH}"
          else
            echo "Creating new legacy-latex-artifacts branch"
            git checkout --orphan "${ARTIFACTS_BRANCH}"
          fi
          git rm -rf . 2>/dev/null || true  # Remove existing files, ignore errors if none exist
        env:
          ARTIFACTS_BRANCH: ${{ steps.set-artifacts-branch.outputs.artifacts_branch }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '!_build'  # Exclude the large _build artifact
          merge-multiple: true

      - name: List generated artifacts
        run: |
          echo "Generated artifacts:"
          find . -name "*.pdf" -ls
          ls -la

      - name: Generate website
        run: |
          cat << EOF > index.html
          <!DOCTYPE html>
          <html>
          <head>
           <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
           <meta name="Author" content="IOHK">
           <title>Legacy LaTeX Artifacts - Formal Ledger Specifications</title>
           <style type="text/css">
            BODY { font-family : monospace, sans-serif;  color: black;}
            P { font-family : monospace, sans-serif; color: black; margin:0px; padding: 0px;}
            A:visited { text-decoration : none; margin : 0px; padding : 0px;}
            A:link    { text-decoration : none; margin : 0px; padding : 0px;}
            A:hover   { text-decoration: underline; background-color : yellow; margin : 0px; padding : 0px;}
            A:active  { margin : 0px; padding : 0px;}
            .VERSION { font-size: small; font-family : arial, sans-serif; }
           </style>
          </head>
          <body>
          	<h1>Legacy LaTeX Artifacts</h1>
          	<p><strong>Branch:</strong> legacy-latex</p>
          	<p><em>This branch contains PDF files generated from legacy LaTeX source code.</em></p>
          	<hr>
          EOF

          tree -H '.'                     \
               -L 2                       \
               --dirsfirst                \
               --hintro=/dev/null         \
               --houtro=/dev/null         \
               --metafirst                \
               --charset utf-8            \
               --timefmt '%d-%b-%Y %H:%M' \
               -I "index.html"            \
               -h -D --du                 \
               >> index.html

          cat << EOF >> index.html
          	<hr>
          	<p class="VERSION">
              Generated from legacy-latex branch commit <a href="https://github.com/intersectmbo/formal-ledger-specifications/commit/${{ github.sha }}">${{ github.sha }}</a>
          	</p>
          	<p><em>PDFs in this branch are used by the main branch CI for artifact distribution.</em></p>
          </body>
          </html>
          EOF

      - name: Commit artifacts
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit --allow-empty -m "Legacy LaTeX artifacts from ${{ github.sha }}"

      - name: Push legacy-latex-artifacts branch
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ steps.set-artifacts-branch.outputs.artifacts_branch }}
            force: true
