name: Delete artifacts branch on PR closed

on:
  pull_request:
    types: [closed]

jobs:
  delete-artifacts-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete artifacts branch
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git push origin --delete "$ARTIFACTS_BRANCH" || echo "Branch $ARTIFACTS_BRANCH does not exist"
        env:
          ARTIFACTS_BRANCH: ${{ github.head_ref }}-artifacts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
