name: Reusable workflow

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: download agda _build
        uses: actions/download-artifact@v4
        with:
          name: _build
          path: _build
      - name: debug
        run: ls -R
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: https://github.com/NixOS/nixpkgs/archive/0da3c44a9460a26d2025ec3ed2ec60a895eb1114.tar.gz
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org/
      - name: build the target ${{ inputs.target }}
        run: |
          nix-shell --run 'fls-shake --trace ${{ inputs.target }}'
          rsync -r --exclude={'**/nix-support','**/lib'} dist/${{ inputs.target }} docs/
      - name: upload docs
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: formal-ledger-${{ inputs.target }}
          path: docs
