name: Shellcheck

# This pipeline runs shellcheck on shell scripts with extension .sh
# in the repository's folder scripts/.

on:
  push:
    branches: [ "master" ]
  pull_request:
  # For running the workflow manually - useful for branches without PRs, for
  # which CI isn't run automatically
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Shellcheck
        uses: workflow/nix-shell-action@v3
        with:
          packages: shellcheck
          script: |
            printf "Checking that shellcheck on all scripts.\n"

            git ls-files scripts/       \
              | grep '\.sh'             \
              | xargs -rd\\n -I {} -- shellcheck {}

            if [ $? -eq 0 ]; then
              printf "Success: all scripts passed shellcheck.\n"
              exit 0
            else
              printf "Failure: some scripts didn't pass shellcheck.\n"
              exit 1
            fi
